import dynamic from "next/dynamic";
import { ReactNode } from "react";

const Plot = dynamic(() => import("react-plotly.js"), { ssr: false, })

export function LeadPlot(props: { className?: string; children: ReactNode }) {
  return (
    <Plot
      data={[
        {
          branchvalues: "total",
          customdata: [
            ["Sean Bailey", "Drago", "Scarpa", "Scarpa"],
            ["Mia Krampl", "Drago", "Scarpa", "Scarpa"],
            ["Zhilu Luo", "Drago", "Scarpa", "Scarpa"],
            [
              "Janja Garnbret",
              "Hiangle",
              "Five Ten",
              "Five Ten",
            ],
            [
              "Yoshiyuki Ogata",
              "Hiangle",
              "Five Ten",
              "Five Ten",
            ],
            ["Ross Fulkerson", "Theory", "La Sportiva", "La Sportiva"],
            ["Oriane Bertone", "Drago", "Scarpa", "Scarpa"],
            ["Chaehyun Seo", "Theory", "La Sportiva", "La Sportiva"],
            ["Jessica Pilz", "Drago", "Scarpa", "Scarpa"],
            [
              "Franziska Sterrer",
              "Hiangle",
              "Five Ten",
              "Five Ten",
            ],
            ["Miho Nonaka", "Hiangle", "Five Ten", "Five Ten"],
            ["Natsuki Tanii", "Solution Comp", "La Sportiva", "La Sportiva"],
            ["Rei Kawamata", "Instinct VSR", "Scarpa", "Scarpa"],
            ["Saki Kikuchi", "Oasi", "Tenaya", "Tenaya"],
            ["Stasa Gejo", "Flagship", "UnParallel", "UnParallel"],
            [
              "Natalia Grossman",
              "Hiangle",
              "Five Ten",
              "Five Ten",
            ],
            ["Maximillian Milne", "Drago", "Scarpa", "Scarpa"],
            ["Ai Mori", "Futura", "La Sportiva", "La Sportiva"],
            ["Jongwon Chon", "Skwama", "La Sportiva", "La Sportiva"],
            ["Ayala Kerem", "Shark 2.0", "Mad Rock", "Mad Rock"],
            ["Colin Duffy", "Shaman", "Evolv", "Evolv"],
            ["Camilla Moroni", "Drago", "Scarpa", "Scarpa"],
            ["Nicolai Uznik", "Skwama", "La Sportiva", "La Sportiva"],
            ["Anze Peharc", "Nitro", "Ocun", "Ocun"],
            ["Mia Aoyagi", "Regulus", "UnParallel", "UnParallel"],
            ["Serika Okawachi", "Futura", "La Sportiva", "La Sportiva"],
            ["Anon Matsufuji", "Drago", "Scarpa", "Scarpa"],
            ["Brooke Raboutou", "Skwama", "La Sportiva", "La Sportiva"],
            ["Keita Dohi", "Shark 2.0", "Mad Rock", "Mad Rock"],
            ["Paul Jenft", "Unknown", "EB", "EB"],
            ["Dohyun Lee", "Skwama", "La Sportiva", "La Sportiva"],
            ["Futaba Ito", "Theory", "La Sportiva", "La Sportiva"],
            ["Tomoa Narasaki", "Flagship", "UnParallel", "UnParallel"],
            [
              "Mejdi Schalck",
              "Hiangle",
              "Five Ten",
              "Five Ten",
            ],
            ["Jakob Schubert", "Solution", "La Sportiva", "La Sportiva"],
            ["Andrea K\u00fcmin", "Drago", "Scarpa", "Scarpa"],
            ["Taisei Homma", "Drago", "Scarpa", "Scarpa"],
            ["Kokoro Fujii", "Hiangle", "Five Ten", "Five Ten"],
            [
              "Yannick Floh\u00e9",
              "Hiangle",
              "Five Ten",
              "Five Ten",
            ],
            ["Hannah Meul", "Drago", "Scarpa", "Scarpa"],
            ["Meichi Narasaki", "Skwama", "La Sportiva", "La Sportiva"],
            ["", "Drago", "Scarpa", "Scarpa"],
            ["", "Flagship", "UnParallel", "UnParallel"],
            ["", "Futura", "La Sportiva", "La Sportiva"],
            ["", "Hiangle", "Five Ten", "Five Ten"],
            ["", "Instinct VSR", "Scarpa", "Scarpa"],
            ["", "Nitro", "Ocun", "Ocun"],
            ["", "Oasi", "Tenaya", "Tenaya"],
            ["", "Regulus", "UnParallel", "UnParallel"],
            ["", "Shaman", "Evolv", "Evolv"],
            ["", "Shark 2.0", "Mad Rock", "Mad Rock"],
            ["", "Skwama", "La Sportiva", "La Sportiva"],
            ["", "Solution", "La Sportiva", "La Sportiva"],
            ["", "Solution Comp", "La Sportiva", "La Sportiva"],
            ["", "Theory", "La Sportiva", "La Sportiva"],
            ["", "Unknown", "EB", "EB"],
            ["", "", "EB", "EB"],
            ["", "", "Evolv", "Evolv"],
            ["", "", "Five Ten", "Five Ten"],
            ["", "", "La Sportiva", "La Sportiva"],
            ["", "", "Mad Rock", "Mad Rock"],
            ["", "", "Ocun", "Ocun"],
            ["", "", "Scarpa", "Scarpa"],
            ["", "", "Tenaya", "Tenaya"],
            ["", "", "UnParallel", "UnParallel"],
            ["", "", "All", "All"],
          ],
          domain: { x: [0.0, 1.0], y: [0.0, 1.0] },
          hovertemplate:
            "%{customdata[0]}<br>%{customdata[3]} %{customdata[1]}<br>Count: %{value}",
          ids: [
            "All/Scarpa/Drago/Sean Bailey",
            "All/Scarpa/Drago/Mia Krampl",
            "All/Scarpa/Drago/Zhilu Luo",
            "All/Five Ten/Hiangle/Janja Garnbret",
            "All/Five Ten/Hiangle/Yoshiyuki Ogata",
            "All/La Sportiva/Theory/Ross Fulkerson",
            "All/Scarpa/Drago/Oriane Bertone",
            "All/La Sportiva/Theory/Chaehyun Seo",
            "All/Scarpa/Drago/Jessica Pilz",
            "All/Five Ten/Hiangle/Franziska Sterrer",
            "All/Five Ten/Hiangle/Miho Nonaka",
            "All/La Sportiva/Solution Comp/Natsuki Tanii",
            "All/Scarpa/Instinct VSR/Rei Kawamata",
            "All/Tenaya/Oasi/Saki Kikuchi",
            "All/UnParallel/Flagship/Stasa Gejo",
            "All/Five Ten/Hiangle/Natalia Grossman",
            "All/Scarpa/Drago/Maximillian Milne",
            "All/La Sportiva/Futura/Ai Mori",
            "All/La Sportiva/Skwama/Jongwon Chon",
            "All/Mad Rock/Shark 2.0/Ayala Kerem",
            "All/Evolv/Shaman/Colin Duffy",
            "All/Scarpa/Drago/Camilla Moroni",
            "All/La Sportiva/Skwama/Nicolai Uznik",
            "All/Ocun/Nitro/Anze Peharc",
            "All/UnParallel/Regulus/Mia Aoyagi",
            "All/La Sportiva/Futura/Serika Okawachi",
            "All/Scarpa/Drago/Anon Matsufuji",
            "All/La Sportiva/Skwama/Brooke Raboutou",
            "All/Mad Rock/Shark 2.0/Keita Dohi",
            "All/EB/Unknown/Paul Jenft",
            "All/La Sportiva/Skwama/Dohyun Lee",
            "All/La Sportiva/Theory/Futaba Ito",
            "All/UnParallel/Flagship/Tomoa Narasaki",
            "All/Five Ten/Hiangle/Mejdi Schalck",
            "All/La Sportiva/Solution/Jakob Schubert",
            "All/Scarpa/Drago/Andrea K\u00fcmin",
            "All/Scarpa/Drago/Taisei Homma",
            "All/Five Ten/Hiangle/Kokoro Fujii",
            "All/Five Ten/Hiangle/Yannick Floh\u00e9",
            "All/Scarpa/Drago/Hannah Meul",
            "All/La Sportiva/Skwama/Meichi Narasaki",
            "All/Scarpa/Drago",
            "All/UnParallel/Flagship",
            "All/La Sportiva/Futura",
            "All/Five Ten/Hiangle",
            "All/Scarpa/Instinct VSR",
            "All/Ocun/Nitro",
            "All/Tenaya/Oasi",
            "All/UnParallel/Regulus",
            "All/Evolv/Shaman",
            "All/Mad Rock/Shark 2.0",
            "All/La Sportiva/Skwama",
            "All/La Sportiva/Solution",
            "All/La Sportiva/Solution Comp",
            "All/La Sportiva/Theory",
            "All/EB/Unknown",
            "All/EB",
            "All/Evolv",
            "All/Five Ten",
            "All/La Sportiva",
            "All/Mad Rock",
            "All/Ocun",
            "All/Scarpa",
            "All/Tenaya",
            "All/UnParallel",
            "All",
          ],
          labels: [
            "Sean Bailey",
            "Mia Krampl",
            "Zhilu Luo",
            "Janja Garnbret",
            "Yoshiyuki Ogata",
            "Ross Fulkerson",
            "Oriane Bertone",
            "Chaehyun Seo",
            "Jessica Pilz",
            "Franziska Sterrer",
            "Miho Nonaka",
            "Natsuki Tanii",
            "Rei Kawamata",
            "Saki Kikuchi",
            "Stasa Gejo",
            "Natalia Grossman",
            "Maximillian Milne",
            "Ai Mori",
            "Jongwon Chon",
            "Ayala Kerem",
            "Colin Duffy",
            "Camilla Moroni",
            "Nicolai Uznik",
            "Anze Peharc",
            "Mia Aoyagi",
            "Serika Okawachi",
            "Anon Matsufuji",
            "Brooke Raboutou",
            "Keita Dohi",
            "Paul Jenft",
            "Dohyun Lee",
            "Futaba Ito",
            "Tomoa Narasaki",
            "Mejdi Schalck",
            "Jakob Schubert",
            "Andrea K\u00fcmin",
            "Taisei Homma",
            "Kokoro Fujii",
            "Yannick Floh\u00e9",
            "Hannah Meul",
            "Meichi Narasaki",
            "Drago",
            "Flagship",
            "Futura",
            "Hiangle",
            "Instinct VSR",
            "Nitro",
            "Oasi",
            "Regulus",
            "Shaman",
            "Shark 2.0",
            "Skwama",
            "Solution",
            "Solution Comp",
            "Theory",
            "Unknown",
            "EB",
            "Evolv",
            "Five Ten",
            "La Sportiva",
            "Mad Rock",
            "Ocun",
            "Scarpa",
            "Tenaya",
            "UnParallel",
            "All",
          ],
          marker: {
            colors: [
              "rgb(102, 197, 204)",
              "rgb(102, 197, 204)",
              "rgb(102, 197, 204)",
              "rgb(248, 156, 116)",
              "rgb(248, 156, 116)",
              "rgb(246, 207, 113)",
              "rgb(102, 197, 204)",
              "rgb(246, 207, 113)",
              "rgb(102, 197, 204)",
              "rgb(248, 156, 116)",
              "rgb(248, 156, 116)",
              "rgb(246, 207, 113)",
              "rgb(102, 197, 204)",
              "rgb(201, 219, 116)",
              "rgb(220, 176, 242)",
              "rgb(248, 156, 116)",
              "rgb(102, 197, 204)",
              "rgb(246, 207, 113)",
              "rgb(246, 207, 113)",
              "rgb(254, 136, 177)",
              "rgb(135, 197, 95)",
              "rgb(102, 197, 204)",
              "rgb(246, 207, 113)",
              "rgb(180, 151, 231)",
              "rgb(220, 176, 242)",
              "rgb(246, 207, 113)",
              "rgb(102, 197, 204)",
              "rgb(246, 207, 113)",
              "rgb(254, 136, 177)",
              "rgb(158, 185, 243)",
              "rgb(246, 207, 113)",
              "rgb(246, 207, 113)",
              "rgb(220, 176, 242)",
              "rgb(248, 156, 116)",
              "rgb(246, 207, 113)",
              "rgb(102, 197, 204)",
              "rgb(102, 197, 204)",
              "rgb(248, 156, 116)",
              "rgb(248, 156, 116)",
              "rgb(102, 197, 204)",
              "rgb(246, 207, 113)",
              "rgb(102, 197, 204)",
              "rgb(220, 176, 242)",
              "rgb(246, 207, 113)",
              "rgb(248, 156, 116)",
              "rgb(102, 197, 204)",
              "rgb(180, 151, 231)",
              "rgb(201, 219, 116)",
              "rgb(220, 176, 242)",
              "rgb(135, 197, 95)",
              "rgb(254, 136, 177)",
              "rgb(246, 207, 113)",
              "rgb(246, 207, 113)",
              "rgb(246, 207, 113)",
              "rgb(246, 207, 113)",
              "rgb(158, 185, 243)",
              "rgb(158, 185, 243)",
              "rgb(135, 197, 95)",
              "rgb(248, 156, 116)",
              "rgb(246, 207, 113)",
              "rgb(254, 136, 177)",
              "rgb(180, 151, 231)",
              "rgb(102, 197, 204)",
              "rgb(201, 219, 116)",
              "rgb(220, 176, 242)",
              "rgba(0, 0, 0, 0)",
            ],
          },
          name: "",
          parents: [
            "All/Scarpa/Drago",
            "All/Scarpa/Drago",
            "All/Scarpa/Drago",
            "All/Five Ten/Hiangle",
            "All/Five Ten/Hiangle",
            "All/La Sportiva/Theory",
            "All/Scarpa/Drago",
            "All/La Sportiva/Theory",
            "All/Scarpa/Drago",
            "All/Five Ten/Hiangle",
            "All/Five Ten/Hiangle",
            "All/La Sportiva/Solution Comp",
            "All/Scarpa/Instinct VSR",
            "All/Tenaya/Oasi",
            "All/UnParallel/Flagship",
            "All/Five Ten/Hiangle",
            "All/Scarpa/Drago",
            "All/La Sportiva/Futura",
            "All/La Sportiva/Skwama",
            "All/Mad Rock/Shark 2.0",
            "All/Evolv/Shaman",
            "All/Scarpa/Drago",
            "All/La Sportiva/Skwama",
            "All/Ocun/Nitro",
            "All/UnParallel/Regulus",
            "All/La Sportiva/Futura",
            "All/Scarpa/Drago",
            "All/La Sportiva/Skwama",
            "All/Mad Rock/Shark 2.0",
            "All/EB/Unknown",
            "All/La Sportiva/Skwama",
            "All/La Sportiva/Theory",
            "All/UnParallel/Flagship",
            "All/Five Ten/Hiangle",
            "All/La Sportiva/Solution",
            "All/Scarpa/Drago",
            "All/Scarpa/Drago",
            "All/Five Ten/Hiangle",
            "All/Five Ten/Hiangle",
            "All/Scarpa/Drago",
            "All/La Sportiva/Skwama",
            "All/Scarpa",
            "All/UnParallel",
            "All/La Sportiva",
            "All/Five Ten",
            "All/Scarpa",
            "All/Ocun",
            "All/Tenaya",
            "All/UnParallel",
            "All/Evolv",
            "All/Mad Rock",
            "All/La Sportiva",
            "All/La Sportiva",
            "All/La Sportiva",
            "All/La Sportiva",
            "All/EB",
            "All",
            "All",
            "All",
            "All",
            "All",
            "All",
            "All",
            "All",
            "All",
            "",
          ],
          values: [
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
            1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 11, 2, 2,
            8, 1, 1, 1, 1, 1, 2, 5, 1, 1, 3, 1, 1, 1, 8, 12, 2, 1, 12, 1, 3,
            41,
          ],
          type: "treemap",
        },
      ]}
      layout={{
        margin: {
          t: 0,
          l: 0,
          b: 0,
          r: 0,
        },
        font: {
          color: "var(--mono12)"
        },
        height: 500,
      }}
      config={{
        displayModeBar: false,
        responsive: true,
        showTips: false
      }}
      style={{
        width: "100%",
        height: "500px"
      }}
    />
  );
}